### ISSUE TITLE
Showing flowing Error in output panel

### ISSUE THREAD

**Issue by mdshifut** [Grimones/vscode-styled-jsx-languageserver#14]
`[Error - 9:29:47 PM] (node:14156) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'kind' of undefined
    at isStyledJsxTag (c:\Users\Yoga\.vscode\extensions\andrewrazumovsky.vscode-styled-jsx-languageserver-1.0.1\server\out\styled-jsx-utils.js:48:31)
    at findStyledJsxTaggedTemplate (c:\Users\Yoga\.vscode\extensions\andrewrazumovsky.vscode-styled-jsx-languageserver-1.0.1\server\out\styled-jsx-utils.js:74:22)
    at Object.getStyledJsx (c:\Users\Yoga\.vscode\extensions\andrewrazumovsky.vscode-styled-jsx-languageserver-1.0.1\server\out\styled-jsx-utils.js:120:40)
    at c:\Users\Yoga\.vscode\extensions\andrewrazumovsky.vscode-styled-jsx-languageserver-1.0.1\server\out\styled-jsx-server-main.js:120:44
[Error - 9:29:47 PM] (node:14156) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
[Error - 9:29:47 PM] (node:14156) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
[Error - 9:29:47 PM] Request textDocument/documentSymbol failed.
  Message: Request textDocument/documentSymbol failed with message: Cannot read property 'kind' of undefined
  Code: -32603 `

**Comment by qumeta** [comment]
+1

**Comment by Svish** [comment]
+1
