### ISSUE TITLE
Request textDocument/completion failed with message: Cannot read property 'kind' of undefined

### ISSUE THREAD

**Issue by Negan1911** [Grimones/vscode-styled-jsx-languageserver#2]
Hi, i'm importing a CSS file with the `to-string-loader` and this library looks like fails with it, but the worst part is that the output tab is always focused.

The usage that i do is:
```
import style from './style.css'
```

and later on the JSX:
```
<React.Fragment>
    <div>Other things here...</Div>
    <style jsx global>
      {style}
    </style>
  </React.Fragment>
```

The output of the console is:
```
[Error - 15:25:44] Request textDocument/codeAction failed.
  Message: Request textDocument/codeAction failed with message: Cannot read property 'kind' of undefined
  Code: -32603 
```

**Comment by Grimones** [comment]
I would appreaciate a minimal project so i can fix it

**Comment by nfantone** [comment]
I came here for this. Same thing happening for me. 

![image](https://user-images.githubusercontent.com/476069/39122745-22d1134a-46f6-11e8-8fc4-a662f3a6cdcf.png)

It keeps popping out every other second.

> I would appreciate a minimal project so i can fix it

@Grimones TBH, all I did was install `vscode-styled-jsx-languageserver` after `vscode-styled-jsx` and this error started showing right away without me doing anything particular.

Using Code `1.22.2` + `node` `v9.11.1`.

**Comment by nfantone** [comment]
@Grimones There are not too many instances on your codebase that are referencing a `.kind` attribute.

The `token` parameter in either one of these functions turns out to be `undefined`:

https://github.com/Grimones/vscode-styled-jsx-languageserver/blob/master/server/src/styled-jsx-utils.ts#L56

https://github.com/Grimones/vscode-styled-jsx-languageserver/blob/master/server/src/styled-jsx-utils.ts#L33

Can you think of any reason why this could happen?

**Comment by atif089** [comment]
I have the same problem. Here is the piece of code that is causing it in my case

```
          <style jsx>
            {`
              .app-container {
                background-color: #fff;
                max-width: 640px;
                margin: auto;
                padding: 20px;
              }
            `}
          </style>
```


Full Component

``` <Layout>
        <div className="app app-container">
          <header className="header">
            <Logo />
          </header>
          <div className="appBody"> Something </div>

          <style jsx>
            {`
              .app-container {
                background-color: #fff;
                max-width: 640px;
                margin: auto;
                padding: 20px;
              }
            `}
          </style>
        </div>
      </Layout>```

**Comment by Grimones** [comment]
Interesting. It should not be undefined as it goes in [while cycle](https://github.com/Grimones/vscode-styled-jsx-languageserver/blob/a60ed8c10ee46657a196205d5f89f4a0fe33ebbe/server/src/styled-jsx-utils.ts#L86)

So when token is undefined, which is a falsy value - cycle should stop.

I guess they have changed something in new versions of vscode. I will try to fix this weekend

**Comment by Grimones** [comment]
Okay, i have found the problem. The problem is addressed to [vscode-styled-jsx](https://github.com/iFwu/vscode-styled-jsx).

This extensions relies on [vscode-styled-jsx](https://github.com/iFwu/vscode-styled-jsx) for parsing the stylesheet between `<style jsx>` tags. In both cases you provided the curly braces goes on the next line after the tag so [vscode-styled-jsx](https://github.com/iFwu/vscode-styled-jsx) cant parse it correctly and language server recieves nothing and falls with error.

For now, just do 
```
<style jsx>{`
   .app-container {
       background-color: #fff;
       max-width: 640px;
       margin: auto;
       padding: 20px;
    }
`}</style>
```

and 
```
<style jsx>{style}</style>
```

I will try to catch this cases to prevent language server from falling with error.

I think that we should move the syntax highlighting from [vscode-styled-jsx](https://github.com/iFwu/vscode-styled-jsx) to this repo and make fixes. It will be better to have all in one extension, with syntax highlight, completions, etc.

**Comment by nfantone** [comment]
@Grimones Thank you for looking into this. I'd like to point out that while your discovery might be causing this issue, I believe it's _one_ scenario of possibly many that can trigger it. I just checked and I don't have any instances in my project where my brackets are placed below the `<style jsx>` element. I'm using `prettier` which automatically formats styles to match your suggestion, so I'm inclined to say that there might be other pesky things worth investigating.

**Comment by Macil** [comment]
I get the same error as OP with this:

```
import textFieldStyle from './textFieldStyle';
...
        <style jsx global>
          {textFieldStyle}
        </style>
```

Removing the newlines and changing it to `<style jsx global>{textFieldStyle}</style>` works around the problem, but I'm using Prettier which insists on putting in newlines like that.

**Comment by Macil** [comment]
Here's a complete file that triggers the issue:

```js
import bar from './bar';

function foo() {
  return (
    <style jsx global>
      {textFieldStyle}
    </style>
  );
}
```

**Comment by ywg-jean** [comment]
@Grimones I was unable to identify an issue on the iFwu/vscode-styled-jsx issue tracker regarding the incorrect parsing you raised. Could you report an issue there for this issue ? I would do it myself but I am not very confident I understand what exactly is broken ...

**Comment by saostad** [comment]
same problem here.
```
[Error - 4:09:43 PM] Request textDocument/documentSymbol failed.
  Message: Request textDocument/documentSymbol failed with message: Cannot read property 'kind' of undefined
  Code: -32603 
[Error - 4:09:43 PM] Request textDocument/codeAction failed.
  Message: Request textDocument/codeAction failed with message: Cannot read property 'kind' of undefined
  Code: -32603 
[Error - 4:09:44 PM] (node:14696) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'kind' of undefined
    at isStyledJsxTag (c:\Users\SOstad\.vscode\extensions\andrewrazumovsky.vscode-styled-jsx-languageserver-1.0.1\server\out\styled-jsx-utils.js:48:31)
    at findStyledJsxTaggedTemplate (c:\Users\SOstad\.vscode\extensions\andrewrazumovsky.vscode-styled-jsx-languageserver-1.0.1\server\out\styled-jsx-utils.js:74:22)
    at Object.getStyledJsx (c:\Users\SOstad\.vscode\extensions\andrewrazumovsky.vscode-styled-jsx-languageserver-1.0.1\server\out\styled-jsx-utils.js:120:40)
    at c:\Users\SOstad\.vscode\extensions\andrewrazumovsky.vscode-styled-jsx-languageserver-1.0.1\server\out\styled-jsx-server-main.js:120:44
[Error - 4:09:44 PM] (node:14696) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
[Error - 4:09:44 PM] (node:14696) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
[Error - 4:09:44 PM] Request textDocument/codeAction failed.
  Message: Request textDocument/codeAction failed with message: Cannot read property 'kind' of undefined
  Code: -32603 
[Error - 4:09:45 PM] Request textDocument/codeAction failed.
  Message: Request textDocument/codeAction failed with message: Cannot read property 'kind' of undefined
  Code: -32603 
[Error - 4:09:52 PM] Request textDocument/codeAction failed.
  Message: Request textDocument/codeAction failed with message: Cannot read property 'kind' of undefined
  Code: -32603 
[Error - 4:09:53 PM] Request textDocument/codeAction failed.
  Message: Request textDocument/codeAction failed with message: Cannot read property 'kind' of undefined
  Code: -32603 

```

**Comment by peckpeck20** [comment]
Same here..

**Comment by spacecakes** [comment]
Very nice to see that you've discovered why this happens. I've been working on a project that uses styled jsx for a few months now and the lack of auto completion really bothers me. 

Unfortunately we also use Prettier which automatically includes line breaks before ``{` and crashes the language server. There is no fix at the moment, right?

**Comment by carlosbaraza** [comment]
Reloading the window fixed it for me `cmd` + `R`

**Comment by carlosbaraza** [comment]
Found my workaround, just ensure that the style tag is opened without leaving an empty line:

### Working:
```
<style jsx>{`
  .my-component {}
`}</style>
```

### NOT Working:
```
<style jsx>
  {`
  .my-component {}
  `}
</style>
```

**Comment by MAPESO** [comment]
Hi all  👋 
Install the following plugin and solve the problem of the error that appeared in the VSCode console

<img width="876" alt="Screen Shot 2019-11-03 at 11 10 28" src="https://user-images.githubusercontent.com/16585386/68089132-70248080-fe2b-11e9-9de3-7dca22137849.png">

this is the plugin that **doesn't work** 😿 
<img width="567" alt="Screen Shot 2019-11-03 at 11 09 40" src="https://user-images.githubusercontent.com/16585386/68089123-60a53780-fe2b-11e9-8545-69730e323c50.png">
